import { Resend } from 'resend';

// Initialize only if API key present to prevent development server crashes
const resendApiKey = process.env.RESEND_API_KEY;
const resend = resendApiKey ? new Resend(resendApiKey) : null;

export async function sendEventConfirmation(
  toEmail: string, 
  firstName: string, 
  eventTitle: string, 
  eventDate: string, 
  eventTime: string, 
  location: string
) {
  if (!resend) {
    // Graceful fallback for local development or missing API keys
    console.log(`\n📧 [MOCK EMAIL SENT TO: ${toEmail}]`);
    console.log(`SUBJECT: Booking Confirmed: ${eventTitle}`);
    console.log(`Hi ${firstName}, your event '${eventTitle}' is confirmed for ${eventDate} at ${eventTime} in ${location}.\n`);
    return { success: true, mocked: true };
  }

  try {
    const data = await resend.emails.send({
      from: 'EventSync Pro <bookings@eventsyncpro.com>', // User will need to verify this domain via Resend Dashboard
      to: [toEmail],
      subject: `Booking Confirmed: ${eventTitle}`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-w: 600px; margin: 0 auto; padding: 20px; color: #1e293b;">
          <div style="text-align: center; margin-bottom: 30px;">
            <div style="background-color: #4f46e5; color: white; padding: 12px; border-radius: 12px; display: inline-block; font-weight: bold; font-size: 24px;">
              EventSync Pro
            </div>
          </div>
          <h2 style="color: #4f46e5; text-align: center; font-size: 28px; margin-bottom: 24px;">Your Event is Confirmed!</h2>
          <p style="font-size: 16px; line-height: 1.6;">Hi <strong>${firstName}</strong>,</p>
          <p style="font-size: 16px; line-height: 1.6;">This is an automated confirmation that your event space has been successfully booked securely in our system. Here are your final details:</p>
          
          <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 12px; margin: 24px 0;">
             <div style="margin-bottom: 12px; font-size: 16px;"><strong>📌 Event Title:</strong> ${eventTitle}</div>
             <div style="margin-bottom: 12px; font-size: 16px;"><strong>📅 Date:</strong> ${eventDate}</div>
             <div style="margin-bottom: 12px; font-size: 16px;"><strong>⏰ Start Time:</strong> ${eventTime}</div>
             <div style="font-size: 16px;"><strong>📍 Location Space:</strong> ${location}</div>
          </div>
          
          <p style="font-size: 16px; line-height: 1.6; color: #475569;">If you need to make any emergency changes or request additional layout accommodations, please contact the administrative reception desk immediately.</p>
          
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 32px 0;" />
          <p style="color: #94a3b8; font-size: 14px; text-align: center;">Automatically generated by your EventSync Pro Management System.</p>
        </div>
      `
    });
    return { success: true, data };
  } catch (error) {
    console.error("Resend API failed to dispatch email:", error);
    return { success: false, error };
  }
}
